### ISSUE TITLE
ppc: compiler runs out of memory compiling icudt53_dat.c

### ISSUE THREAD

**Issue by srl295** [srl295/node#4]
consider allowing more modes besides genccode

this is when using `full-icu`

**Comment by sxa555** [comment]
This workaround doesn't appear to be adequate for compiling icudt54_dat.c but it's ok with v53
I've been able to compile it with LDR_CNTRL=MAXDATA=0xB0000000@DSA, which seems a slightly ridiculous amount to have to increase it by (It didn't work with 0xA0000000) but it did complete the compilation of that file.

**Comment by srl295** [comment]
@sxa555 ok, I should look into changing the generation mode above. I forget which mode AIX can use, but it can at least split the file into multiple pieces. 

Acutally joyent/node#8979 affects this also (or kicks the can down the road) by decreasing the size of the data. 

A workaround woul dbe to use the appropriate http://apps.icu-project.org/datacustom/ and uncheck "charset mapping" and "break iteratror" and "Rule Based Number Format" and "Transliterators" ,  generate for ICU4C, and overwrite the resulting file in `icu/source/data/in`.

**Comment by srl295** [comment]
Moved to https://github.com/joyent/node/issues/9047
